services:
  elasticsearch:
    image: ghcr.io/mi-dpla/combine-docker/elasticsearch:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    environment:
      - cluster.name=combine-elasticsearch
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.enabled=false
      - http.max_initial_line_length=5m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"


  mongo:
    image: ghcr.io/mi-dpla/combine-docker/mongo:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    volumes:
      - mongodata:/data/db
    expose:
      - "27017"
    command: "--config /etc/mongod.conf"


  mysql:
    image: ghcr.io/mi-dpla/combine-docker/mysql:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: combine
      MYSQL_TCP_PORT: 3307
      MARIADB_AUTO_UPGRADE: true
      MARIADB_USER: combine
      MARIADB_PASSWORD: combine
      MARIADB_DATABASE: combine
    expose:
      - "3307"
    volumes:
      - mysqldata:/var/lib/mysql/

  redis:
    image: redis:4.0

  hadoop-namenode:
    image: ghcr.io/mi-dpla/combine-docker/hadoop-namenode:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    volumes:
      - type: volume
        source: hdfs
        target: /hdfs
        read_only: false
    expose:
      - "8020"
    command:  /opt/hadoop/bin/hdfs --config /opt/hadoop/etc/hadoop namenode
    # Use entrypoint when errors about hdfs not being configured/present
    # entrypoint: bash /opt/hadoop/entrypoint_namenode.sh

  hadoop-datanode:
    image: ghcr.io/mi-dpla/combine-docker/hadoop-datanode:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    depends_on:
      - hadoop-namenode
    expose:
      - "50071"
      - "50075"
    command:  /opt/hadoop/bin/hdfs --config /opt/hadoop/etc/hadoop datanode

  django:
    image: ghcr.io/mi-dpla/combine-docker/django:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    depends_on:
      - mysql
    expose:
      - "8000"
    command:  bash -c "nohup pyjxslt 6767 & > /tmp/pyjxslt.out && python /opt/combine/manage.py runserver 0.0.0.0:8000"
    # if starting the app gives an error about needing to run migrations, uncomment this line
    #entrypoint: bash /tmp/combine_db_prepare.sh
    volumes:
      - type: volume
        source: hdfs
        target: /hdfs
        read_only: true
      - type: volume
        source: hadoop_binaries
        target: /opt/hadoop
        read_only: true
      - type: volume
        source: spark_binaries
        target: /opt/spark
        read_only: true
      - type: volume
        source: livy_binaries
        target: /opt/livy
        read_only: true
      - type: volume
        source: combine_home
        target: /home/combine
        read_only: false # owner
      - type: volume
        source: combine_python_env
        target: /opt/conda/envs/combine
        read_only: false # owner
      - type: volume
        source: combine_tmp
        target: /tmp
        read_only: false

  celery:
    image: ghcr.io/mi-dpla/combine-docker/celery:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    volumes:
      - type: volume
        source: hdfs
        target: /hdfs
        read_only: true
      - type: volume
        source: hadoop_binaries
        target: /opt/hadoop
        read_only: true
      - type: volume
        source: spark_binaries
        target: /opt/spark
        read_only: true
      - type: volume
        source: livy_binaries
        target: /opt/livy
        read_only: true
      - type: volume
        source: combine_home
        target: /home/combine
        read_only: false # owner
      - type: volume
        source: combine_python_env
        target: /opt/conda/envs/combine
        read_only: false # owner
      - type: volume
        source: combine_tmp
        target: /tmp
        read_only: false
    working_dir: /opt/combine
    command: supervisord -c /etc/supervisor/supervisord.conf -n
    expose:
      - "9001"
    depends_on:
      - redis

  livy:
    image: ghcr.io/mi-dpla/combine-docker/livy:04fbc964b22e76e30169fee1b22aea9ddb7f41f0
    depends_on:
      - django
    volumes:
      - type: volume
        source: hdfs
        target: /hdfs
        read_only: true
      - type: volume
        source: hadoop_binaries
        target: /opt/hadoop
        read_only: true
      - type: volume
        source: spark_binaries
        target: /opt/spark
        read_only: false # owner of /opt/spark when Livy only
      - type: volume
        source: livy_binaries
        target: /opt/livy
        read_only: false # owner of dir
      - type: volume
        source: combine_home
        target: /home/combine
        read_only: false
      - type: volume
        source: combine_python_env
        target: /opt/conda/envs/combine
        read_only: true
      - type: volume
        source: combine_tmp
        target: /tmp
        read_only: false
    expose:
      - "8998"
      - "4040"
    command:  bash -c "nohup pyjxslt 6767 & > /tmp/pyjxslt.out && /opt/livy/bin/livy-server"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./combine/combine/static:/static
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    depends_on:
      - django
      - celery
      - livy
      - elasticsearch
      - hadoop-datanode

volumes:

  # non-volatile
  esdata:
    driver: local
  mongodata:
    driver: local
  mysqldata:
    driver: local
  hdfs:
    driver: local
  combine_home:
    driver: local

  # volatile
  combine_python_env:
    driver: local
  hadoop_binaries:
    driver: local
  spark_binaries:
    driver: local
  livy_binaries:
    driver: local
  combine_tmp:
    driver: local
