FROM ghcr.io/mi-dpla/combine-docker/spark-cluster-base:latest

ARG COMBINE_BRANCH
ENV COMBINE_BRANCH=$COMBINE_BRANCH
ARG SCALA_VERSION
ENV SCALA_VERSION=$SCALA_VERSION

RUN apt-get update --fix-missing && \
  mkdir -p /etc/apt/keyrings && \
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
  curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
   gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
   --dearmor && \
  echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] http://repo.mongodb.org/apt/debian buster/mongodb-org/6.0 main" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list && \
    apt-get update && \
    apt-get install -y wget bzip2 ca-certificates curl gnupg git libmariadb3 libmariadb-dev libmariadb-dev-compat gcc libkrb5-dev libxml2-dev libxslt1-dev libmariadb-java python3-dev default-mysql-client vim make mongodb-database-tools nodejs && \
    npm install elasticdump -g && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    ln -s /usr/lib/x86_64-linux-gnu/libmariadb.so.3 /usr/lib/x86_64-linux-gnu/libmariadbclient.so.18 && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_23.11.0-2-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
  /opt/conda/bin/conda create -n combine python=3.8 --yes
ENV PATH=/opt/conda/envs/combine/bin:$PATH

# copy Combine app submodule
RUN cd /opt \
  && git clone https://github.com/MI-DPLA/combine \
  && cd combine \
  && git checkout ${COMBINE_BRANCH} \
  && cp combine/localsettings.py.docker combine/localsettings.py

# Copy scripts
COPY combine/combine.sql /tmp/combine.sql
COPY combine/combine_db_prepare.sh /tmp/combine_db_prepare.sh
COPY mysql/root.my.cnf /etc/.my.cnf

RUN cd /opt/combine && \
  pip install -r requirements.txt && \
  pip install livy && \
  pip install git+https://github.com/MI-DPLA/es2csv.git@python3
