---
name: "Build images"

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'which image to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - mongo
          - spark-cluster-base
          - hadoop-namenode
          - hadoop-datanode
          - django
          - celery
          - livy
          - mysql

env:
  COMBINE_BRANCH: kubernetify
  COMBINE_DJANGO_HOST_PORT: 8000
  COMBINE_DOCKER_VERSION: v0.11
  ELASTICSEARCH_HADOOP_CONNECTOR_VERSION: 7.1.1
  HADOOP_VERSION: 2.7.5
  HADOOP_VERSION_SHORT: 2.7
  SCALA_VERSION: 2.11
  SPARK_VERSION: 2.3.2
  SPARK_GIT: branch-2.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          lfs: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mongo image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'mongo' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./mongo
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/mongo:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/mongo:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/mongo:latest'
          file: ./mongo/Dockerfile

      - name: Build elasticsearch image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'elasticsearch' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./elasticsearch
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/elasticsearch:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/elasticsearch:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/elasticsearch:latest'
          file: ./elasticsearch/Dockerfile

      - name: Build spark-cluster-base image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'spark-cluster-base' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./spark_cluster_base
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/spark-cluster-base:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/spark-cluster-base:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/spark-cluster-base:latest'
          file: ./spark_cluster_base/Dockerfile
          build-args: |
            SPARK_VERSION=2.3.2
            HADOOP_VERSION_SHORT=2.7
            ELASTICSEARCH_HADOOP_CONNECTOR_VERSION=7.1.1

      - name: Build hadoop-namenode image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'hadoop-namenode' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./hadoop
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/hadoop-namenode:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/hadoop-namenode:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/hadoop-namenode:latest'
          file: ./hadoop/Dockerfile
          build-args: |
            HADOOP_VERSION=2.7.5

      - name: Build hadoop-datanode image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'hadoop-datanode' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./hadoop
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/hadoop-datanode:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/hadoop-datanode:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/hadoop-datanode:latest'
          file: ./hadoop/Dockerfile
          build-args: |
            HADOOP_VERSION=2.7.5

      - name: Build django image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'django' || github.events.inputs.image == 'celery' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/django:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/django:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/django:latest'
          file: ./combine/Dockerfile.prod
          build-args: |
            SCALA_VERSION=2.11
            COMBINE_BRANCH=kubernetify

      - name: Build celery image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'celery' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/celery:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/celery:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/celery:latest'
          file: ./celery/Dockerfile

      - name: Build livy image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'livy' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/livy:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/livy:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/livy:latest'
          file: ./livy/Dockerfile
          build-args: |
            SCALA_VERSION=2.11
            ELASTICSEARCH_HADOOP_CONNECTOR_VERSION=7.1.1

      - name: Build mysql image and push to GitHub Container Registry
        if: ${{ github.event.inputs.image == 'all' || github.event.inputs.image == 'mysql' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ./mysql
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/mysql:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/mysql:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/mysql:latest'
          file: ./mysql/Dockerfile
