---
name: "Build images"

on:
  workflow_dispatch:
  push:
    branches:
      - 'kubernetify'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mongo image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./mongo
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/mongo:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/mongo:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/mongo:latest'
          file: ./mongo/Dockerfile

      - name: Build spark-cluster-base image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./spark_cluster_base
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/spark-cluster-base:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/spark-cluster-base:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/spark-cluster-base:latest'
          file: ./spark_cluster_base/Dockerfile

      - name: Build hadoop-namenode image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./hadoop
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/hadoop-namenode:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/hadoop-namenode:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/hadoop-namenode:latest'
          file: ./hadoop/Dockerfile

      - name: Build hadoop-datanode image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./hadoop
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/hadoop-datanode:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/hadoop-datanode:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/hadoop-datanode:latest'
          file: ./hadoop/Dockerfile

      - name: Build django image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/django:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/django:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/django:latest'
          file: ./combine/Dockerfile

      - name: Build celery image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/celery:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/celery:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/celery:latest'
          file: ./celery/Dockerfile

      - name: Build livy image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mi-dpla/combine-docker/livy:${{ github.sha }}, ghcr.io/mi-dpla/combine-docker/livy:${{ github.ref_name }}, ghcr.io/mi-dpla/combine-docker/livy:latest'
          file: ./livy/Dockerfile
